/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "amphitheatre": {
    "base": "amphitheatre",
    "width": 3924,
    "height": 2628,
    "fallbackWidth": 1920,
    "fallbackHeight": 1286,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "balcony": {
    "base": "balcony",
    "width": 4128,
    "height": 3096,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cathedral": {
    "base": "cathedral",
    "width": 3008,
    "height": 2000,
    "fallbackWidth": 800,
    "fallbackHeight": 532,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "circus": {
    "base": "circus",
    "width": 480,
    "height": 640,
    "fallbackWidth": 480,
    "fallbackHeight": 640,
    "widths": [
      320,
      480
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 2000,
    "height": 1330,
    "fallbackWidth": 1920,
    "fallbackHeight": 1277,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coastal": {
    "base": "coastal",
    "width": 2000,
    "height": 1330,
    "fallbackWidth": 1920,
    "fallbackHeight": 1277,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 2280,
    "height": 3420,
    "fallbackWidth": 1920,
    "fallbackHeight": 2880,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 5184,
    "height": 3888,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 640,
    "height": 480,
    "fallbackWidth": 640,
    "fallbackHeight": 480,
    "widths": [
      320,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 2592,
    "height": 1944,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food-and-wine": {
    "base": "food-and-wine",
    "width": 2592,
    "height": 1944,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food-market": {
    "base": "food-market",
    "width": 4096,
    "height": 2304,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "forum": {
    "base": "forum",
    "width": 2048,
    "height": 1329,
    "fallbackWidth": 800,
    "fallbackHeight": 519,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero": {
    "base": "hero",
    "width": 3440,
    "height": 2168,
    "fallbackWidth": 1920,
    "fallbackHeight": 1210,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 3440,
    "height": 2168,
    "fallbackWidth": 1920,
    "fallbackHeight": 1210,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "highlights": {
    "base": "highlights",
    "width": 3924,
    "height": 2628,
    "fallbackWidth": 800,
    "fallbackHeight": 536,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 3924,
    "height": 2628,
    "fallbackWidth": 800,
    "fallbackHeight": 536,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "nature": {
    "base": "nature",
    "width": 2000,
    "height": 1330,
    "fallbackWidth": 1920,
    "fallbackHeight": 1277,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 3440,
    "height": 2168,
    "fallbackWidth": 1920,
    "fallbackHeight": 1210,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "old-town": {
    "base": "old-town",
    "width": 4160,
    "height": 3120,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "photography": {
    "base": "photography",
    "width": 3924,
    "height": 2628,
    "fallbackWidth": 1920,
    "fallbackHeight": 1286,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 3072,
    "height": 2304,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "rambla": {
    "base": "rambla",
    "width": 640,
    "height": 480,
    "fallbackWidth": 640,
    "fallbackHeight": 480,
    "widths": [
      320,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 3072,
    "height": 2304,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 2592,
    "height": 1944,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
